# Generated by Django 5.1.5 on 2025-01-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
